kind: pipeline
name: RAD KERNEL BUILD OLDCAM

clone:
  disable: true

steps:
- name: oldcam
  image: archlinux:latest
  environment:
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export TG_BOT_API"
    - pacman -Sy base-devel bc curl zip wget git --noconfirm
    - git clone --depth=1 --quiet https://github.com/theradcolor/android_kernel_xiaomi_whyred.git -b ${DRONE_COMMIT_BRANCH} source && cd source
    - git clone --depth=1 --quiet https://github.com/theradcolor/lazyscripts.git -b master
    - script -c "bash -x lazyscripts/ci-scripts/ci-rad --oldcam --aosp-clang" rad-oldcam-build.log && bash /drone/src/source/lazyscripts/ci-scripts/logger


---
kind: pipeline
name: RAD KERNEL BUILD NEWCAM

clone:
  disable: true

steps:
- name: newcam
  image: archlinux:latest
  environment:
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export TG_BOT_API"
    - pacman -Sy base-devel bc curl zip wget git --noconfirm
    - git clone --depth=1 --quiet https://github.com/theradcolor/android_kernel_xiaomi_whyred.git -b ${DRONE_COMMIT_BRANCH} source && cd source
    - git clone --depth=1 --quiet https://github.com/theradcolor/lazyscripts.git -b master
    - script -c "bash -x lazyscripts/ci-scripts/ci-rad --oldcam --aosp-clang" rad-newcam-build.log && bash /drone/src/source/lazyscripts/ci-scripts/logger